### ISSUE TITLE
Allow multiple projectKey values

### ISSUE THREAD

**Issue by scorpiodawg** [ryanvade/enforce-pr-title-style-action#16]
It would be nice to include more than one `projectKey` so that one of a predefined set of projects is allowed and nothing else. For example:

```yaml
- name: Enforce Jira Issue Key in Pull Request Title
  uses: ryanvade/enforce-pr-title-style-action@v1
  with:
    projectKeys: #this is an array, note the plural name
      - AB
      - CD
      - DE
```
