### ISSUE TITLE
Support for multiple key references in PR title.

### ISSUE THREAD

**Issue by jackson-chris** [ryanvade/enforce-pr-title-style-action#31]
I opened a PR with the following title:
```
feat(helm charts): DEV-69378. DEV-72222. Add python worker helm charts and required pipeline scripts.
```
which failed. I'm assuming it's the back to back ticket references without a comment inbetween, because altering it to the following worked:
```
feat(helm charts): DEV-69378 and DEV-72222. Add python worker helm charts and required pipeline scripts.
```

I believe the former should be a valid title however as sometimes you may bundle two closely related stories into a single PR. Understandably this may be a topic that sees differences of opinion but perhaps a flag could be added that allows for such?

NOTE: The following configuration for the action was used:
```
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: ryanvade/enforce-pr-title-style-action@v2
        with:
          projectKey: 'DEV'
          keyAnywhereInTitle: 'true'
```
